version: '2'
services:
  baseimage:
    build: ./baseimage
    image: hyperledger/fabric-baseimage:latest

  membersrvc:
    image: ibmblockchain/fabric-membersrvc:${ARCH_TAG}
    extends:
      file: base/membersrvc.yaml
      service: membersrvc

  vp:
    image: ibmblockchain/fabric-peer:${ARCH_TAG}
    extends:
      file: base/peer-secure-base.yaml
      service: peer-secure-base
    ports:
      - "7050:7050"
      - "7051:7051"
      - "7053:7053"
    environment:
      - CORE_PEER_ID=vp0
      - CORE_SECURITY_ENROLLID=vp
      - CORE_SECURITY_ENROLLSECRET=f3489fy98ghf
    links:
      - membersrvc

